### ISSUE TITLE
Compatibility With Mongo 2.6? (Failed to create index)

### ISSUE THREAD

**Issue by flipxfx** [spohlenz/mongomodel#29]
We are using MongoModel, Wheelhouse and are unable to get them working with Mongo 2.6. Are these compatible?

```
mongo (1.9.2) lib/mongo/collection.rb:1086:in `rescue in generate_indexes'
mongo (1.9.2) lib/mongo/collection.rb:1079:in `generate_indexes'
mongo (1.9.2) lib/mongo/collection.rb:552:in `create_index'
mongomodel (0.5.2) lib/mongomodel/support/instrumented_collection.rb:97:in `block in create_index'
activesupport (3.2.17) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.17) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.17) lib/active_support/notifications.rb:123:in `instrument'
mongomodel (0.5.2) lib/mongomodel/support/instrumented_collection.rb:125:in `instrument'
mongomodel (0.5.2) lib/mongomodel/support/instrumented_collection.rb:96:in `create_index'
mongomodel (0.5.2) lib/mongomodel/document/indexes.rb:40:in `block in ensure_indexes!'
mongomodel (0.5.2) lib/mongomodel/document/indexes.rb:39:in `each'
mongomodel (0.5.2) lib/mongomodel/document/indexes.rb:39:in `ensure_indexes!'
mongomodel (0.5.2) lib/mongomodel/support/scope.rb:192:in `ensure_indexes!'
mongomodel (0.5.2) lib/mongomodel/support/scope.rb:159:in `_find'
mongomodel (0.5.2) lib/mongomodel/support/scope.rb:165:in `_find_and_instantiate'
mongomodel (0.5.2) lib/mongomodel/support/scope.rb:43:in `to_a'
mongomodel (0.5.2) lib/mongomodel/support/scope/finder_methods.rb:29:in `first'
mongomodel (0.5.2) lib/mongomodel/document/scopes.rb:14:in `first'
wheelhouse-core (1.0.18) app/models/wheelhouse/site.rb:37:in `for_request'
wheelhouse-core (1.0.18) lib/wheelhouse/middleware/set_site.rb:21:in `site_for'
wheelhouse-core (1.0.18) lib/wheelhouse/middleware/set_site.rb:12:in `call'
request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
lib/middleware/caching_with_request_forgery_protection.rb:8:in `call'
lib/middleware/default_headers.rb:8:in `call'
```

**Comment by spohlenz** [comment]
This should be resolved by updating to mongomodel 0.5.4 and wheelhouse 1.1.4.
